export const LOGIN_ROUTE: string = '/login'
export const REGISTRATION_ROUTE: string = '/registration'
export const MAIN_ROUTE: string = '/main' 
export const ROCKET_ROUTE: string = '/rocket'
export const USER_ROUTE: string = '/user/:id'
export const NEW_PLACE: string = '/addplace'
